list.Add( "NPCUsableWeapons", { class = "weapon_ak47",	       title = "AK-47" }  )
list.Add( "NPCUsableWeapons", { class = "weapon_deagle",	   title = "Desert Eagle" }  )
list.Add( "NPCUsableWeapons", { class = "weapon_fiveseven",	   title = "Five-seveN" }  )
list.Add( "NPCUsableWeapons", { class = "weapon_glock18",	   title = "Glock 18" }  )
list.Add( "NPCUsableWeapons", { class = "weapon_m4a1",	       title = "M4A1" }  )
list.Add( "NPCUsableWeapons", { class = "weapon_mac10",	       title = "Ingram MAC10" }  )
list.Add( "NPCUsableWeapons", { class = "weapon_mp5",	       title = "HK MP5" }  )
list.Add( "NPCUsableWeapons", { class = "weapon_para",	       title = "M249 Para" }  )
list.Add( "NPCUsableWeapons", { class = "weapon_pumpshotgun",  title = "Pump Shotgun" }  )
list.Add( "NPCUsableWeapons", { class = "weapon_tmp",	       title = "Steyr TMP" }  )